# Redirect non-www -> www (HTTP)
server {
  listen 80;
  server_name tiktok.io.vn;
  return 301 https://www.tiktok.io.vn$request_uri;
}

# FE: www.tiktok.io.vn (HTTP) -> chuyển HTTPS & chấp nhận ACME
server {
  listen 80;
  server_name www.tiktok.io.vn;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  return 301 https://$host$request_uri;
}

# API: api.tiktok.io.vn (HTTP) -> chuyển HTTPS & ACME
server {
  listen 80;
  server_name api.tiktok.io.vn;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  return 301 https://$host$request_uri;
}

# ================= HTTPS =================

# FE: www.tiktok.io.vn -> tikweb:80
server {
  listen 443 ssl http2;
  server_name www.tiktok.io.vn;

  ssl_certificate     /etc/letsencrypt/live/www.tiktok.io.vn/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.tiktok.io.vn/privkey.pem;

  client_max_body_size 50m;

  location / {
    proxy_pass http://tikweb:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

# API: api.tiktok.io.vn -> tikapi:4000
map $http_upgrade $connection_upgrade { default upgrade; '' close; }
server {
  listen 443 ssl http2;
  server_name api.tiktok.io.vn;

  ssl_certificate     /etc/letsencrypt/live/api.tiktok.io.vn/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.tiktok.io.vn/privkey.pem;

  client_max_body_size 100m;

  location / {
    proxy_pass http://tikapi:4000;
    proxy_http_version 1.1;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300;
  }
}
